#!/bin/bash

name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '37 14,15,16,17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: install proj
      run: |-
        sudo apt-get update
        sudo apt-get install proj
    - name: Fetch latest data
      run: |-
        mappingurl="https://api.misoenergy.org/MISORTWDDataBroker/DataBrokerServices.asmx?messageType=getvectorsource&nodeTypes=GEN,INT,LZN"
        mapping=$(curl $mappingurl -L --compressed)
        echo $mapping > "mapping.json"
        items=$(echo "$mapping" | jq -c -r '.f|.[]')
        settings=$(echo $mapping | jq '.proj' | tr -d '"' ) 
        mkdir -p forecastGridData
        mkdir -p observations
        for i in $items
        do            
          north=$(echo $i | jq '.g.c[1]' )
          east=$(echo $i | jq '.g.c[0]' )
          coor=$(echo "${east} ${north}" | proj -I $settings -f "%.4f" -s)
          coorclean=$(echo $coor| sed 's/ /,/g')
          url="https://api.weather.gov/points/${coorclean}"
          filename=$(echo $i | jq '.p | join("_")' | tr -d '"')
          info=$(curl $url -L)
          urldata=$(echo $info | grep -zoP '(?<=forecastGridData\": \").*(?=\",\s\"obs)')
          outfile="forecastGridData/${filename}.json"
          curl $urldata  -L > "${outfile}"
          urlobs=$(echo $info | grep -zoP '(?<=observationStations\": \").*(?=\",\s\"rela)')
          obs=$(curl $urlobs -L)
          station=$(echo $obs | grep -Po 'observationStations\": \[ "\K[^"]*')
          outfile="observations/${filename}.json"
          curl ${station}"/observations/latest" -L > "${outfile}"
        done
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u --rfc-3339=seconds)
        git commit -m "Latest data (UTC): ${timestamp}" || exit 0
        git push
